feature: #126 정류장 시간표 기능에 요일 파라미터 추가
1sTeam/all-knu-backend pull request #127
Opened 2024-03-06 03:01 UTC by zkdl2727

- ### 기능 수정 및 추가 

  1. **요일별 시간표 조회 기능 추가** : 기존 정류장에 대한 시간표만 조회 가능 -> 요일 정보를 입력해 해당 요일의 시간표를 조회 가능 -> `GET /api/v2/knu/shuttle/timetable` API를 수정하였으며, 요일 정보는 URL에 포함하여 전달. 예) `/api/v2/knu/shuttle/timetable?day=월요일`
  2. **요일별 시간표 등록 기능 추가** : `registerStationTimetable` 메서드가 요일 정보를 받아 해당 요일의 시간표를 등록하도록 수정 => 특정 요일에 대한 시간표를 등록 할 수 있도록 기능 수정.
  3. **요일별 시간표 삭제 기능 추가** : `DELETE /knu/shuttle/{station}/{day}/{time}` API가 요일 정보를 매개변수로 받아 해당 요일의 시간표를 삭제하도록 수정 =>특정 요일의 시간표를 삭제할 수 있도록 기능 수정.

- ### 테스트 코드 수정 
  - 위의 기능 수정에 따라, 시간표 등록 및 삭제, 조회 테스트 코드도 일괄적으로 수정.

2024-03-06 10:26 UTC, suhongkim98 requested changes

2024-03-06 10:26 UTC, suhongkim98 commented on src/main/java/com/allknu/backend/shuttle/domain/StationTimetable.java
> +    private String day;
단순히 day 필드만 추가할 경우, 시간표가 수정될 때마다 월화수목금 시간표 모두 갱신해줘야하는 불편함이 생길 것 같아요.

다음과 같이 하는게 어떨까요?
1. 시간표를 생성하고 해당하는 요일들을 지정할 수 있다.
2. 시간표 간에 요일은 중복될 수 없다.
3. 조회하고자 하는 요일을 넣고 GET API를 호출하면 해당 요일의 시간표를 조회한다.

그리고 라이브환경에서는 JPA ddl auto가 validate 이기 때문에 flyway쪽도 수정해줘야할 것 같습니다.

2024-03-06 12:29 UTC, zkdl2727 commented on src/main/java/com/allknu/backend/shuttle/domain/StationTimetable.java
> +    private String day;
StationTImeTable과 day를 다대다 관계로 표현하는 방향을 말씀하신게 맞나요??

2024-03-06 14:05 UTC, zkdl2727 commented on src/main/java/com/allknu/backend/shuttle/domain/StationTimetable.java
> +    private String day;
추가적으로 버전 업 관련 pr내용 마무리 됐는데, 먼저 머지 해도 될까요??

2024-03-08 10:56 UTC, suhongkim98 commented on src/main/java/com/allknu/backend/shuttle/domain/StationTimetable.java
> +    private String day;
넹넹 문제 없으면 머지해도 됩니다.

StationTImeTable과 day는 `일대다`가 될 것 같아요.

2024-03-21 14:11 UTC, merged